### ISSUE TITLE
Can't mount 64GB exFAT

### ISSUE THREAD

**Issue by aronson** [ktoonsez/KT-SGS4#1]
I've had no luck getting my 64GB exFAT-formatted flash card to mount on this kernel.

I'm using the GE Final v1 ROM by Jamal2367. If I use the ausdim kernel my SD card auto-mounts like normal, but if I load with your kernel the card is never mounted. The storage screen just shows the 'Mount SD card' option, and when I choose it it claims to be checking the drive for errors before it stops and does nothing.

I really like your kernel and the work you've done, I just wish I could get my exFAT working. Is there a known limitation of 64 GB sd cards and exFAT?

**Comment by aronson** [comment]
Fixed it myself. I had my card formatted as a GPT drive when I needed to use MBR to get the partition to mount.

**Comment by ktoonsez** [comment]
There is no limitations on it. It is just brand specific. Samsung brand
works 100% of the time. The others are hit and miss.

**Comment by aronson** [comment]
I was using a class 10 SanDisk card, for reference. Thankfully it works perfectly now!

**Comment by ktoonsez** [comment]
Awesome. Glad to hear it.
