### ISSUE TITLE
CONFIG_PPP_ASYNC

### ISSUE THREAD

**Issue by morlac** [ktoonsez/KT-SGS4#4]
Hi Ktoonsez,
could you enable CONFIG_PPP_ASYNC=m in your SGS4-Active config?
with this as a module one could use the phone with the VW-Premium handsfree for data-connectivity via http://android-rsap.de

thanks in advance,
Morlac

**Comment by ktoonsez** [comment]
Never heard of VW-Premium handsfree but yes I can add it.  What about the CONFIG_PPP_SYNC_TTY flag?

**Comment by ktoonsez** [comment]
Never heard of VW-Premium handsfree but yes I can add it.  What about
the CONFIG_PPP_SYNC_TTY
flag?

**Comment by morlac** [comment]
As far as I know this is not needed for what I want.

**Comment by ktoonsez** [comment]
Its done and will be in next release
