### ISSUE TITLE
[REQUEST]CIFS/NFS Modules

### ISSUE THREAD

**Issue by Rusk85** [ktoonsez/KT-SGS4#5]
Hi ktoonsez!

Thanks for the great work. Running it on my phone. One thing I am missing are CIFS/NFS modules so I can mount my network shares via my VPN.  I tried building them myself using your repo but it seems you have referenced "/home/ktoonsez/workspace/com.ktoonsez.KTweaker.apk" which I dont have. Considering that I have never build a kernel or a module for a kernel before I thought I just ask you if you'd be willing to include them?
Again thanks for your time and the great work! :)

**Comment by ktoonsez** [comment]
Tell me which one you want added, CIFS is already enabled but the are many, many modules to CIFS.  Get the specific ones you are looking for and I will add them :-)

**Comment by Rusk85** [comment]
Well I am using NFSv4 and Samba (ARCH: extra/samba 4.1.4-1). For the latter I am not sure what protocol version that exactly is. If thats not enough information I am happy to provide more or help in some other form. 
Thank you so much!
Out of sheer curiosity where are you taking the module source from to compile it against your custom kernel? Is it the AOSP?

**Comment by Rusk85** [comment]
_bump_

**Comment by ktoonsez** [comment]
Source is a mix of Samsung and AOSP.  I will need all the kernel flags that are required from your app.  Easiest thing would be asking the developer of the app what kernel flags need to be turned on for it to work.
